### ISSUE TITLE
New projects for theHunterCOTW fail at processing.

### ISSUE THREAD

**Issue by Swooz777** [kk49/deca#124]
Starting new projects in deca_gui.exe for theHunterCOTW_F.exe fail at processing.

Traceback (most recent call last):
  File "deca\gui\main.py", line 462, in project_new
  File "deca\db_processor.py", line 41, in vfs_structure_new
  File "deca\db_processor.py", line 71, in vfs_structure_prep
  File "deca\db_processor.py", line 315, in process
  File "deca\db_processor.py", line 564, in process_by_ftype_match
  File "deca\db_commands.py", line 135, in do_map
  File "deca\db_commands.py", line 266, in mp_issue_commands
Exception: Manager: PROCESSING FAILED

**Comment by kk49** [comment]
The latest version on Steam works for me. Can you post your log.txt file or come to the discord https://discord.gg/KTZ7UvRRkw and post the log.txt file there?

**Comment by Swooz777** [comment]
[log.txt](https://github.com/kk49/deca/files/8079780/log.txt)
also posted in #thehunter

**Comment by Swooz777** [comment]
Running it on the same disk as the cotw.exe made it work.

**Comment by kk49** [comment]
It looks like the problem was that it ran out of space. I need to make that more clear. At least print the actual error at the end when it says processing failed.
